# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_result_int_int <- function(agg, grp, order_by, value, start, end) {
    .Call(`_RollingTime_get_result_int_int`, agg, grp, order_by, value, start, end)
}

get_result_int_num <- function(agg, grp, order_by, value, start, end) {
    .Call(`_RollingTime_get_result_int_num`, agg, grp, order_by, value, start, end)
}

get_result_num_int <- function(agg, grp, order_by, value, start, end) {
    .Call(`_RollingTime_get_result_num_int`, agg, grp, order_by, value, start, end)
}

get_result_num_num <- function(agg, grp, order_by, value, start, end) {
    .Call(`_RollingTime_get_result_num_num`, agg, grp, order_by, value, start, end)
}

#'@export
#'@result_ts The sorted POSIXct vector of result timestamp.
#'@value_ts The POSIXct vector of timestamp of data.
#'@value The numeric vector of data.
#'@interval_size The length of the interval in second.
#'@return A numeric vector. The \code{i}-th element is the sum of \code{value} whose corresponding timestamp is
NULL

time_interval_sum <- function(result_ts, value_ts, value, interval_size) {
    .Call(`_RollingTime_time_interval_sum`, result_ts, value_ts, value, interval_size)
}

